from __future__ import annotations

from collections import deque
from datetime import datetime, timezone

from pydantic import BaseModel, Field


class TokenUsage(BaseModel):
    prompt_tokens: int = 0
    completion_tokens: int = 0  # means tokens generated by the model
    total_tokens: int = 0


class CostEstimate(BaseModel):
    """Cost estimate for a request, based on token usage and model pricing."""

    input_cost: float = 0.0
    output_cost: float = 0.0
    total_cost: float = 0.0
    currency: str = "CNY"  # means currency of the model pricing


class RequestMetrics(BaseModel):
    """Metrics and metadata for a single model generation request."""

    latency_ms: int
    usage: TokenUsage = Field(default_factory=TokenUsage)
    cost: CostEstimate = Field(default_factory=CostEstimate)
    validation_ok: bool = True
    validation_error: str | None = None


class GenerationTrace(BaseModel):
    """Trace of a single model generation request, including metrics and metadata."""

    request_id: str
    session_id: str
    model: str
    prompt_template: str
    metrics: RequestMetrics
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class InMemoryTraceStore:
    """In-memory trace store for model generation requests."""

    def __init__(self, max_events: int = 200) -> None:
        self._events: deque[GenerationTrace] = deque(maxlen=max(1, max_events))

    def append(self, trace: GenerationTrace) -> None:
        self._events.append(trace)

    def list_events(self, limit: int = 50) -> list[GenerationTrace]:
        return list(self._events)[-max(1, limit) :]


def estimate_cost(
    usage: TokenUsage,
    input_token_price_per_1m: float,
    output_token_price_per_1m: float,
) -> CostEstimate:
    input_cost = usage.prompt_tokens * input_token_price_per_1m / 1_000_000
    output_cost = usage.completion_tokens * output_token_price_per_1m / 1_000_000
    total_cost = input_cost + output_cost
    return CostEstimate(
        input_cost=round(input_cost, 8),
        output_cost=round(output_cost, 8),
        total_cost=round(total_cost, 8),
    )
